import logging
from pathlib import Path
import pandas as pd

# Define project root dynamically to ensure path resolution from any execution directory
project_root = Path(__file__).resolve().parents[1]

def setup_logger():
    """Configures standard output logging."""
    logger = logging.getLogger(__name__)
    logger.setLevel(logging.INFO)
    handler = logging.StreamHandler()
    formatter = logging.Formatter("%(asctime)s - %(levelname)s - %(message)s")
    handler.setFormatter(formatter)
    if not logger.handlers:
        logger.addHandler(handler)
    return logger

logger = setup_logger()

def load_datasets(raw_dir: Path) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Loads the intermediate Parquet files generated by Task 1 and Task 2."""
    df_cafef = pd.DataFrame()
    df_vst = pd.DataFrame()
    
    cafef_path = raw_dir / "cafef_board.parquet"
    vst_path = raw_dir / "vietstock_board.parquet"
    
    if cafef_path.exists():
        df_cafef = pd.read_parquet(cafef_path)
    if vst_path.exists():
        df_vst = pd.read_parquet(vst_path)
        
    return df_cafef, df_vst

def squash_duplicates(df: pd.DataFrame) -> pd.DataFrame:
    """
    Consolidates multiple roles held by a single individual into a single 'Golden Row'.
    
    Why: Corporate board members frequently hold concurrent positions (e.g., Chairman and CEO).
    Grouping by the deterministic name key and concatenating roles with ' / ' ensures 
    Entity Integrity (one row per person per company) without losing role information.
    """
    if df.empty: return df
    
    group_cols = ['ticker', 'exchange', 'person_name_canonical', 'person_name_key']
    
    # Retain the first encountered value for non-grouping columns
    agg_dict = {col: 'first' for col in df.columns if col not in group_cols and col != 'role'}
    
    # Custom aggregation for the 'role' column: join unique roles with a slash
    agg_dict['role'] = lambda x: ' / '.join(pd.Series(x).dropna().astype(str).unique())
    
    return df.groupby(group_cols, as_index=False).agg(agg_dict)

def resolve_conflicts(row: pd.Series) -> pd.Series:
    """
    Row-level Conflict Resolution Strategy applied after the Outer Join.
    
    Resolution Rules:
    1. Person Name & Role: Prioritize CafeF as it generally has more consistent naming conventions.
    2. Demographics (Age, Edu): Prioritize Vietstock as it provides richer supplementary data.
    3. Metrics: Assigns 'source_agreement' flags and quantitative 'confidence_score's 
       (1.0 = Match, 0.8 = Single Source, 0.6 = Conflict) to quantify data reliability.
    """
    merge_status = row['_merge']
    
    # Case 1: Record exists ONLY in CafeF
    if merge_status == 'left_only':
        row['source_agreement'] = 'cafef_only'
        row['confidence_score'] = 0.8
        row['person_name_golden'] = row['person_name_cafef']
        row['role_golden'] = row['role_cafef']
        row['age_golden'] = row['age_cafef']
        row['education_golden'] = row['education_cafef']
        
    # Case 2: Record exists ONLY in Vietstock
    elif merge_status == 'right_only':
        row['source_agreement'] = 'vietstock_only'
        row['confidence_score'] = 0.8
        row['person_name_golden'] = row['person_name_vst']
        row['role_golden'] = row['role_vst']
        row['age_golden'] = row['age_vst']
        row['education_golden'] = row['education_vst']
        
    # Case 3: Record exists in BOTH sources -> Apply enrichment and conflict checks
    else:
        row['person_name_golden'] = row['person_name_cafef'] 
        
        # Enrichment Strategy: Vietstock typically has better demographic data
        row['age_golden'] = row['age_vst'] if pd.notna(row['age_vst']) else row['age_cafef']
        row['education_golden'] = row['education_vst'] if pd.notna(row['education_vst']) and str(row['education_vst']).strip() != "" else row['education_cafef']

        # Compare concatenated role strings
        role_cafef = str(row['role_cafef']).lower()
        role_vst = str(row['role_vst']).lower()
        
        # Consensus check: If roles are identical or one encompasses the other
        if role_cafef == role_vst or role_cafef in role_vst or role_vst in role_cafef:
            row['source_agreement'] = 'both'
            row['confidence_score'] = 1.0
            # Prefer the more descriptive (longer) role string if they agree
            row['role_golden'] = row['role_cafef'] if len(role_cafef) >= len(role_vst) else row['role_vst']
        else:
            # Conflict detected: Assign lower confidence and default to CafeF as the primary source
            row['source_agreement'] = 'conflict'
            row['confidence_score'] = 0.6
            row['role_golden'] = row['role_cafef'] 

    return row

def main():
    raw_dir = project_root / "data" / "raw"
    final_dir = project_root / "data" / "final"
    final_dir.mkdir(parents=True, exist_ok=True)
    
    logger.info("Starting Task 3: Merge & Deduplicate datasets...")
    df_cafef, df_vst = load_datasets(raw_dir)
    
    if df_cafef.empty and df_vst.empty:
        logger.error("Both source datasets are empty. Aborting merge.")
        return

    # CRITICAL STEP: Deduplicate before merging to ensure a strict 1:1 relationship
    df_cafef = squash_duplicates(df_cafef)
    df_vst = squash_duplicates(df_vst)

    # Join keys utilizing the deterministic normalized name
    join_cols = ['ticker', 'exchange', 'person_name_key', 'person_name_canonical']
    
    # Outer Join to capture all records, using an indicator to track the source of origin
    merged_df = pd.merge(
        df_cafef, 
        df_vst, 
        on=join_cols, 
        how='outer', 
        suffixes=('_cafef', '_vst'),
        indicator=True
    )
    
    # Inject missing supplementary columns if Vietstock completely failed
    for col in ['shares', 'tenure']:
        if col not in merged_df.columns:
            merged_df[col] = None

    # Apply row-wise conflict resolution
    golden_df = merged_df.apply(resolve_conflicts, axis=1)
    
    # Extract Vietstock-exclusive fields
    golden_df['shares_golden'] = golden_df['shares'] if 'shares' in golden_df.columns else None
    golden_df['tenure_golden'] = golden_df['tenure'] if 'tenure' in golden_df.columns else None
    
    # Reshape dataframe to strictly match the Data Dictionary schema
    final_columns = [
        'ticker', 'exchange', 'person_name_golden', 'person_name_canonical', 
        'role_golden', 'age_golden', 'education_golden', 'shares_golden', 'tenure_golden',
        'source_agreement', 'confidence_score'
    ]
    
    golden_df = golden_df[final_columns].rename(columns={
        'person_name_golden': 'person_name',
        'role_golden': 'role',
        'age_golden': 'age',
        'education_golden': 'education',
        'shares_golden': 'shares',
        'tenure_golden': 'tenure'
    })
    
    # ==========================================
    # STRICT SCHEMA ENFORCEMENT & TYPE CASTING
    # ==========================================
    # Why: Parquet is a strictly typed columnar format. If numeric columns contain 
    # string placeholders or mixed types (e.g., object), downstream analytical queries will fail.
    
    # 1. Float for quantitative scores
    golden_df['confidence_score'] = golden_df['confidence_score'].astype(float)
    
    # 2. Nullable Integer ('Int64') for metrics to safely handle missing values without converting to float
    golden_df['age'] = pd.to_numeric(golden_df['age'], errors='coerce').astype('Int64')
    
    if 'shares' in golden_df.columns:
        # Strip string artifacts (e.g., thousands separators) before casting
        golden_df['shares'] = golden_df['shares'].astype(str).str.replace(',', '', regex=False)
        golden_df['shares'] = pd.to_numeric(golden_df['shares'], errors='coerce').astype('Int64')
        
    # 3. String normalization: Nullify pandas string artifacts ('nan', 'None')
    text_cols = [
        'ticker', 'exchange', 'person_name', 'person_name_canonical', 
        'role', 'education', 'tenure', 'source_agreement'
    ]
    for col in text_cols:
        if col in golden_df.columns:
            golden_df[col] = golden_df[col].astype(str)
            golden_df[col] = golden_df[col].replace({'nan': None, 'None': None, '<NA>': None})
            
    # Export to the required assessment path
    output_path = final_dir / "board_golden.parquet"
    golden_df.to_parquet(output_path, index=False)
    
    logger.info(f"Task 3 Complete! Golden dataset generated at: {output_path}")
    
    # Generate inline quality metrics for terminal review
    logger.info("-" * 30)
    logger.info(" QUALITY REPORT STATS ")
    logger.info(f"Total Unique Golden Records: {len(golden_df)}")
    logger.info("Source Agreement Distribution:")
    for key, val in golden_df['source_agreement'].value_counts().items():
        logger.info(f" - {key}: {val} rows ({val/len(golden_df)*100:.1f}%)")
    logger.info("-" * 30)

if __name__ == "__main__":
    main()